insert into communities (name) values ('User-friendly');
insert into communities (name) values ('Profit-focused');
insert into communities (name) values ('human-resource');
insert into communities (name) values ('Focused');
insert into communities (name) values ('Ameliorated');
insert into communities (name) values ('moratorium');
insert into communities (name) values ('artificial intelligence');
insert into communities (name) values ('Seamless');
insert into communities (name) values ('non-volatile');
insert into communities (name) values ('software');
insert into communities (name) values ('protocol');
insert into communities (name) values ('tertiary');
insert into communities (name) values ('productivity');
insert into communities (name) values ('Right-sized');
insert into communities (name) values ('Versatile');
insert into communities (name) values ('real-time');
insert into communities (name) values ('Persistent');
insert into communities (name) values ('Operative');
insert into communities (name) values ('architecture');
insert into communities (name) values ('5th generation');
insert into communities (name) values ('Synchronised');
insert into communities (name) values ('Graphical User Interface');
insert into communities (name) values ('regional');
insert into communities (name) values ('interactive');
insert into communities (name) values ('client-driven');
insert into communities (name) values ('Integrated');
insert into communities (name) values ('Down-sized');
insert into communities (name) values ('attitude');
insert into communities (name) values ('Future-proofed');
insert into communities (name) values ('context-sensitive');
insert into communities (name) values ('application');
insert into communities (name) values ('human-resource');
insert into communities (name) values ('middleware');
insert into communities (name) values ('needs-based');
insert into communities (name) values ('pricing structure');
insert into communities (name) values ('uniform');
insert into communities (name) values ('Versatile');
insert into communities (name) values ('Horizontal');
insert into communities (name) values ('customer loyalty');
insert into communities (name) values ('array');
insert into communities (name) values ('Networked');
insert into communities (name) values ('initiative');
insert into communities (name) values ('Multi-lateral');
insert into communities (name) values ('holistic');
insert into communities (name) values ('tangible');
insert into communities (name) values ('project');
insert into communities (name) values ('Quality-focused');
insert into communities (name) values ('zero defect');
insert into communities (name) values ('24 hour');
insert into communities (name) values ('groupware');
insert into communities (name) values ('monitoring');
insert into communities (name) values ('attitude');
insert into communities (name) values ('bi-directional');
insert into communities (name) values ('directional');
insert into communities (name) values ('multi-state');
insert into communities (name) values ('orchestration');
insert into communities (name) values ('Integrated');
insert into communities (name) values ('Centralized');
insert into communities (name) values ('utilisation');
insert into communities (name) values ('Seamless');
insert into communities (name) values ('collaboration');
insert into communities (name) values ('Intuitive');
insert into communities (name) values ('web-enabled');
insert into communities (name) values ('knowledge user');
insert into communities (name) values ('challenge');
insert into communities (name) values ('Switchable');
insert into communities (name) values ('Inverse');
insert into communities (name) values ('flexibility');
insert into communities (name) values ('projection');
insert into communities (name) values ('moderator');
insert into communities (name) values ('even-keeled');
insert into communities (name) values ('24/7');
insert into communities (name) values ('optimizing');
insert into communities (name) values ('data-warehouse');
insert into communities (name) values ('Profound');
insert into communities (name) values ('algorithm');
insert into communities (name) values ('Networked');
insert into communities (name) values ('Universal');
insert into communities (name) values ('Pre-emptive');
insert into communities (name) values ('Progressive');
insert into communities (name) values ('Inverse');
insert into communities (name) values ('instruction set');
insert into communities (name) values ('Virtual');
insert into communities (name) values ('synergy');
insert into communities (name) values ('encoding');
insert into communities (name) values ('secured line');
insert into communities (name) values ('uniform');
insert into communities (name) values ('global');
insert into communities (name) values ('project');
insert into communities (name) values ('Decentralized');
insert into communities (name) values ('Seamless');
insert into communities (name) values ('process improvement');
insert into communities (name) values ('needs-based');
insert into communities (name) values ('framework');
insert into communities (name) values ('forecast');
insert into communities (name) values ('system engine');
insert into communities (name) values ('framework');
insert into communities (name) values ('Assimilated');
insert into communities (name) values ('Horizontal');
insert into communities (name) values ('internet solution');
insert into communities (name) values ('function');
insert into communities (name) values ('6th generation');
insert into communities (name) values ('Compatible');
insert into communities (name) values ('protocol');
insert into communities (name) values ('Progressive');
insert into communities (name) values ('initiative');
insert into communities (name) values ('interactive');
insert into communities (name) values ('algorithm');
insert into communities (name) values ('Reverse-engineered');
insert into communities (name) values ('Function-based');
insert into communities (name) values ('model');
insert into communities (name) values ('bifurcated');
insert into communities (name) values ('Re-contextualized');
insert into communities (name) values ('stable');
insert into communities (name) values ('static');
insert into communities (name) values ('Expanded');
insert into communities (name) values ('multi-tasking');
insert into communities (name) values ('Graphical User Interface');
insert into communities (name) values ('extranet');
insert into communities (name) values ('maximized');
insert into communities (name) values ('bi-directional');
insert into communities (name) values ('Enterprise-wide');
insert into communities (name) values ('productivity');
insert into communities (name) values ('client-driven');
insert into communities (name) values ('real-time');
insert into communities (name) values ('incremental');
insert into communities (name) values ('4th generation');
insert into communities (name) values ('fault-tolerant');
insert into communities (name) values ('bottom-line');
insert into communities (name) values ('attitude');
insert into communities (name) values ('Phased');
insert into communities (name) values ('fault-tolerant');
insert into communities (name) values ('Graphical User Interface');
insert into communities (name) values ('superstructure');
insert into communities (name) values ('explicit');
insert into communities (name) values ('scalable');
insert into communities (name) values ('system engine');
insert into communities (name) values ('intangible');
insert into communities (name) values ('system engine');
insert into communities (name) values ('protocol');
insert into communities (name) values ('artificial intelligence');
insert into communities (name) values ('foreground');
insert into communities (name) values ('content-based');
insert into communities (name) values ('client-driven');
insert into communities (name) values ('knowledge base');
insert into communities (name) values ('projection');
insert into communities (name) values ('Cloned');
insert into communities (name) values ('model');
insert into communities (name) values ('flexibility');
insert into communities (name) values ('content-based');
